# Generated by Django 4.0 on 2022-10-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('periodo', models.CharField(choices=[('1', 'Primeiro Período'), ('2', 'Segundo Período'), ('3', 'Terceiro Período'), ('4', 'Quarto Período'), ('5', 'Quinto Período')], max_length=1)),
                ('descricao', models.TextField()),
                ('pesquisa', models.TextField()),
            ],
        ),
    ]
