# Generated by Django 4.0 on 2022-11-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bookup_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookup',
            name='editora',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookup',
            name='site_editora',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
