# Generated by Django 4.0 on 2022-10-21 01:38

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bookup_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookup',
            name='upload',
            field=models.FileField(upload_to='uploads/', validators=[home.models.BookUp.validate_file_extension]),
        ),
    ]
