# Generated by Django 4.1.5 on 2023-02-01 00:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('publisher', models.CharField(max_length=100, null=True, verbose_name='Editora')),
                ('publisher_website', models.URLField(null=True, verbose_name='Site da Editora')),
                ('period', models.CharField(choices=[('1', 'Primeiro Período'), ('2', 'Segundo Período'), ('3', 'Terceiro Período'), ('4', 'Quarto Período'), ('5', 'Quinto Período'), ('6', 'Sexto Período'), ('7', 'Setimo Período'), ('8', 'Quinto Período'), ('9', 'Quinto Período'), ('10', 'Quinto Período')], max_length=2, verbose_name='Período')),
                ('book', models.FileField(null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Upload do Livro')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='InfoBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookups.book')),
            ],
            options={
                'verbose_name': 'Descrição do livro',
                'verbose_name_plural': 'Descrições dos Livros',
            },
        ),
        migrations.CreateModel(
            name='Finder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('find', models.CharField(max_length=100, verbose_name='Pesquisa')),
                ('infobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookups.infobook')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
            },
        ),
    ]
